export default {
  slug: 'v561-audit-fixes',
  title_ru: 'v5.6.1 — Багфиксы по архитектурному аудиту',
  title_en: 'v5.6.1 — Audit bug fixes',
  body_ru: 'Провели полный аудит кодовой базы: фронт, бэк, WS, PWA, 3D. Нашли и закрыли 7 багов.\n\n## Push-уведомления вели на старый домен\nПосле ребрендинга в server/ws.js оставался hardcoded URL snatch-highrise.com. Теперь highriseheist.com.\n\n## /api/auth/refresh принимал JWT без exp\nСамодельный токен без exp давал NaN > N = false и проходил. Добавили typeof exp === number.\n\n## sendPushTo молча глушил ошибки\nОшибки VAPID, 429, сетевые терялись. Теперь логируются в error_reports.\n\n## Victory City 3D: TDZ при раннем клике\nintroStart объявлялся внутри animate(), pointerup-handler получал ReferenceError до первого RAF.\n\n## Matchmaking: зависшие комнаты\nКомнаты из findMatch не имели room.created, GC их не чистил. Копились при разрыве двух WS.\n\n## middleware.lastSeenCache рос без лимита\nЧистилась только rateLimits-мапа. Добавили LRU 20k записей.\n\n## Service Worker: упрощён activate\nУсловие k !== CACHE_NAME || k.startsWith(OLD) было всегда true. Упростили.\n\n## bricks.js: дубль ALTER TABLE\nТри try ALTER дублировали миграцию 8 из db.js. Убраны.',
  body_en: 'Full audit of the codebase: frontend, backend, WS, PWA, 3D. Found and fixed 7 bugs.\n\n## Push notifications pointed to old domain\nAfter the rebrand server/ws.js still had hardcoded URL snatch-highrise.com. Now highriseheist.com.\n\n## /api/auth/refresh accepted JWTs without exp\nA handcrafted token without exp made NaN > N = false and slipped through. Added typeof exp === number check.\n\n## sendPushTo silenced errors\nVAPID, 429, network errors were lost. Now logged to error_reports.\n\n## Victory City 3D: TDZ on early click\nintroStart was declared inside animate(), pointerup-handler got ReferenceError before the first RAF.\n\n## Matchmaking: stale rooms\nfindMatch rooms had no room.created, GC could not reap them. Accumulated on double-WS disconnect.\n\n## middleware.lastSeenCache grew without bound\nOnly rateLimits had LRU. Added LRU 20k entries.\n\n## Service Worker: simplified activate\nThe condition k !== CACHE_NAME || k.startsWith(OLD) was always true. Simplified.\n\n## bricks.js: duplicate ALTER TABLE\nThree try ALTER duplicated migration 8 from db.js. Removed.',
  tag: 'release',
  created_at: '2026-04-14 18:00:00',
}
