export default {
  slug: 'v570-achievement-rarity',
  title_ru: 'v5.7.0 — Achievement Rarity, живой процент держателей',
  title_en: 'v5.7.0 — Achievement Rarity, live percentage of holders',
  body_ru: 'Закрыли Issue #6 — полноценная реализация рарности ачивок.\n\n## Как работает\nКаждая ачивка показывает реальный процент игроков, которые её получили, и tier по порогам:\n- legendary: менее 1% держателей\n- epic: менее 5%\n- rare: менее 20%\n- common: 20% и выше\n\nБаза для расчёта — только активные игроки с games_played ≥ 1.\n\n## Endpoints\n- GET /api/achievements/rarity — публичный, возвращает { total, rarity, computedAt }\n- GET /api/achievements/me (auth) — ачивки юзера с rarity merged\n\nОдин SQL с GROUP BY и JOIN через индекс idx_achievements_user. Кэш 5 минут in-memory + Cache-Control на клиенте.\n\n## Фронт\nHook useAchievementRarity — sessionStorage кэш 5 минут + дедупликация parallel-фетчей (10 бейджей = 1 запрос).\n\nКарточки в ProfileAchievements обогащаются живым holders перед рендером.\n\n## Вторая волна аудита\n- chat-limits: LRU для lastSent Map (защита от memory leak)\n- Notification API: title под брендом Highrise Heist (было 4 места)\n- Notification tag префикс snatch- заменён на highrise-',
  body_en: 'Closed Issue #6 — full implementation of achievement rarity.\n\n## How it works\nEach achievement shows the real percentage of players who unlocked it, and a tier by thresholds:\n- legendary: less than 1% holders\n- epic: less than 5%\n- rare: less than 20%\n- common: 20% or more\n\nCalculation base — only active players with games_played >= 1.\n\n## Endpoints\n- GET /api/achievements/rarity — public, returns { total, rarity, computedAt }\n- GET /api/achievements/me (auth) — user achievements with rarity merged\n\nOne SQL with GROUP BY and JOIN via idx_achievements_user. 5-minute in-memory cache + Cache-Control on client.\n\n## Frontend\nHook useAchievementRarity — sessionStorage cache 5 minutes + parallel-fetch deduplication (10 badges = 1 request).\n\nProfileAchievements cards are enriched with live holders before rendering.\n\n## Second audit wave\n- chat-limits: LRU for lastSent Map (memory leak protection)\n- Notification API: title under Highrise Heist brand (was 4 places)\n- Notification tag prefix snatch- replaced with highrise-',
  tag: 'release',
  created_at: '2026-04-14 22:00:00',
}
