export default {
  slug: 'v572-arena-races',
  title_ru: 'Турниры стали честнее',
  title_en: 'Tournaments are now fair',
  body_ru: 'Чинили серьёзный баг в турнирах Арены, который тихо портил рейтинг. Вкратце: когда оба игрока матча одновременно нажимали «я выиграл», игра иногда засчитывала результат дважды. У одного рейтинг шёл в плюс на двойную сумму, у другого — в минус тоже на двойную. Сетка турнира в редких случаях ехала.\n\nТеперь такого не будет: только первое нажатие что-то меняет, второе вежливо игнорируется. Проверили все похожие места в коде турниров — нашли ещё три похожих ситуации (двойное начисление XP за топ-3, дубли матчей на следующем раунде, неровная жеребьёвка) и тоже починили.\n\nЕсли в прошлых турнирах у вас был странный скачок рейтинга — это было оно. Никакой ретроактивной правки не делаем (это слишком рискованно для базы), но дальше всё считается ровно.\n\nЖеребьёвка первого раунда тоже стала по-настоящему случайной — раньше она имела небольшой перекос, и одни и те же игроки чаще оказывались в начале сетки.',
  body_en: 'Fixed a serious bug in Arena tournaments that was quietly corrupting ratings. In short: when both players in a match clicked “I won” at the same time, the game sometimes counted the result twice. One player got double the rating change up, the other double down. The bracket occasionally got skewed.\n\nThis cannot happen now: only the first click changes anything, the second is politely ignored. We checked all similar places in tournament code — found three more (double XP for top 3, duplicate matches in the next round, biased pairings) and fixed those too.\n\nIf in past tournaments you had a strange rating jump — that was it. We are not retroactively fixing the numbers (too risky for the database), but from now on everything counts cleanly.\n\nThe first round draw also became truly random — there used to be a slight bias in pairings.',
  tag: 'release',
  created_at: '2026-04-15 10:00:00',
}
