export default {
  slug: 'v572-arena-races',
  title_ru: 'v5.7.2 — Hotfix: 4 race condition в турнирной логике Арены',
  title_en: 'v5.7.2 — Hotfix: 4 race conditions in Arena tournament logic',
  body_ru: 'Критический hotfix. Нашли и исправили четыре race condition’а в server/routes/arena.js, которые портили рейтинг и XP при одновременных запросах от обоих игроков матча.\n\n## 1. Dual-report — двойной подсчёт рейтинга\n\nВ POST /api/arena/result был check-then-act. Если оба игрока жали «я выиграл» одновременно (типичный сценарий — оба доиграли партию и сразу репортят), оба SELECT’а возвращали winner_id = null, оба проходили проверку, оба делали UPDATE. Итог: arena_matches перезаписывался два раза, а score, wins, losses в arena_participants инкрементировались дважды. Сетка турнира ехала, рейтинг фейкался.\n\nФикс: атомарный UPDATE с guard’ом — UPDATE arena_matches SET winner_id=?, result=? WHERE id=? AND winner_id IS NULL. Проверяем .changes — только один запрос фактически применяется, второй получает 409 без побочных эффектов на participants. Классический SQL optimistic concurrency control.\n\n## 2. Double round advance — дублирующие матчи\n\nАналогичная проблема на следующем уровне. Когда параллельные /result закрывали разные последние матчи раунда, оба видели allDone === true и оба начинали генерировать следующий раунд.\n\nФикс: guard на arena_tournaments.current_round — UPDATE … SET current_round=? WHERE id=? AND current_round=?. Только тот запрос, который реально продвинул раунд, генерирует матчи.\n\n## 3. Double XP для top-3\n\nТо же самое в финальном раунде — XP +200/+100/+50 для top-3 мог начислиться дважды. Guard через status=\'playing\' в finish UPDATE.\n\n## 4. Смещённый shuffle первого раунда\n\nПервоначальная разбивка на пары была через parts.sort(() => Math.random() - 0.5) — анти-паттерн JavaScript’а. Array.sort ожидает consistent comparator. Рандомный comparator в V8 даёт смещённое распределение.\n\nФикс: классический Fisher-Yates shuffle. Равномерное распределение, O(n).\n\n## Итог\n\nОдин коммит c073bd0 — 4 точечных фикса. API не изменилось, все клиенты совместимы. Существующие arena_tournaments не ломаются.\n\nAndroid: versionCode=59, versionName=5.7.2.',
  body_en: 'Critical hotfix. Found and fixed four race conditions in server/routes/arena.js that were corrupting ratings and XP on simultaneous requests from both match players.\n\n## 1. Dual-report — double rating credit\n\nPOST /api/arena/result had check-then-act. If both players pressed “I won” simultaneously (typical scenario — both finish the game and report immediately), both SELECTs returned winner_id = null, both passed the check, both performed UPDATE. Result: arena_matches was overwritten twice, and score, wins, losses in arena_participants were incremented twice. Tournament bracket got skewed, ratings faked.\n\nFix: atomic UPDATE with guard — UPDATE arena_matches SET winner_id=?, result=? WHERE id=? AND winner_id IS NULL. Check .changes — only one request actually applies, the second gets 409 with no side effects on participants. Classic SQL optimistic concurrency control.\n\n## 2. Double round advance — duplicate matches\n\nSame problem at the next level. When parallel /result closed different last matches of the round, both saw allDone === true and both started generating the next round.\n\nFix: guard on arena_tournaments.current_round — UPDATE … SET current_round=? WHERE id=? AND current_round=?. Only the request that actually advanced the round generates matches.\n\n## 3. Double XP for top-3\n\nSame thing in the final round — top-3 XP +200/+100/+50 could be credited twice. Guard via status=\'playing\' in finish UPDATE.\n\n## 4. Biased first-round shuffle\n\nInitial pairing was via parts.sort(() => Math.random() - 0.5) — a JavaScript anti-pattern. Array.sort expects a consistent comparator. Random comparator gives biased distribution in V8.\n\nFix: classic Fisher-Yates shuffle. Uniform distribution, O(n).\n\n## Summary\n\nSingle commit c073bd0 — 4 targeted fixes. API unchanged, all clients compatible. Existing arena_tournaments do not break.\n\nAndroid: versionCode=59, versionName=5.7.2.',
  tag: 'release',
  created_at: '2026-04-15 10:00:00',
}
