export default {
  slug: 'v595-golden-rush',
  title_ru: 'Golden Rush — 4 игрока, 9 стоек, одна высотка',
  title_en: 'Golden Rush — 4 players, 9 stands, one highrise',
  body_ru: 'Месяц копали новый режим — Golden Rush. Это Highrise Heist на четверых: 9 стоек крестом, у каждого игрока две свои (ближняя «order=1» и дальняя «order=2»), в центре общая золотая. Правило-нерв: дальнюю нельзя замкнуть пока ближняя открыта. Собрал обе — претендуешь на центр, первый в очереди забирает +15 очков.\n\nИграть можно двумя способами. Hot-seat на /goldenrush — один телефон, четыре человека по очереди тапают. Онлайн на /goldenrush-online — матчмейкинг ждёт 4 игрока, режим выбираешь сам: 2v2 (команды по диагонали, есть тим-чат) или 4-FFA (каждый за себя). Сервер валидирует каждый ход, читеров не пустит.\n\nЗа каждый сыгранный онлайн-матч капают кирпичи: +2 просто за участие, +10 если победил (в 2v2 — обоим в выигравшей команде), +3 если замкнул центр. Сдался в середине матча — ничего не получил. В конце партии сразу видно сколько начислили и за что.\n\nНа /goldenrush-top — лидерборды по победам, сыгранным играм и взятиям центра. Там же твоя личная статистика, последние твои матчи и публичная лента: кто с кем только что сыграл и с каким счётом. Лидерборд пустой — будь первым в истории.\n\nФизическая настольная версия игры идёт параллельно — мой партнёр Александр работает над картонным вариантом для издателей. Цифровая версия помогает обкатать правила: всё что странно играет в онлайне, будет странно играть и на столе.\n\nПопутно закрыли большой security-аудит (60 пунктов). Переписали сезонные сбросы на UTC, обернули в транзакции все начисления кирпичей, перевели чат на filter v2, добавили admin-audit лог, починили ECDSA-верификацию AdMob SSV, таймеры теперь тикают серверно даже если оппонент ушёл в офлайн. Это незаметная работа, но от неё зависит честность рейтинга и корректность балансов.\n\nДальше — ждём первый реальный плейтест. По его результатам крутим числа (скоринг, капы, награды) и решаем делать ли AI для 4-FFA (дорого по компьюту, нужен validated demand). Рейтинг MMR для GR появится когда наберётся хотя бы 100 сыгранных матчей, чтобы было что калибровать.',
  body_en: 'Spent a month digging a new mode — Golden Rush. It is Highrise Heist for four: 9 stands in a cross, each player owns two (near “order=1”, far “order=2”), and a shared golden one in the center. The key rule: you cannot close the far stand while the near one is open. Close both — you join the queue for the center, the first eligible player takes +15 points.\n\nTwo ways to play. Hot-seat on /goldenrush — one phone, four people taking turns. Online on /goldenrush-online — matchmaking waits for 4 players, you pick the mode yourself: 2v2 (teams sit across the diagonal, with a team chat) or 4-FFA (everyone for themselves). Every move is validated by the server — no way to cheat.\n\nEvery online match pays out bricks: +2 just for participating, +10 for winning (in 2v2 both teammates get it), +3 for capturing the center. Resign mid-game and you get nothing. You see the breakdown right after the match.\n\nOn /goldenrush-top — leaderboards by wins, games played and center captures. Same page shows your personal stats, your recent matches and a public feed of who just played whom. Leaderboard is empty — be first in history.\n\nThe physical board game is moving in parallel — my partner Alexander is polishing the cardboard version for publishers. The digital build is a testbed for the rules: whatever feels awkward online will feel awkward at the table too.\n\nWe also closed a large security audit (60 items) along the way. Rewrote season resets to UTC, wrapped all brick awards in transactions, moved chat to filter v2, added an admin-audit log, fixed ECDSA verification for AdMob SSV, made timers tick server-side even when the opponent goes offline. Invisible work, but fair ratings and correct balances depend on it.\n\nWhat is next — we wait for the first real playtest. Based on it we will tune the numbers (scoring, caps, rewards) and decide whether to train an AI for 4-FFA (expensive compute, needs validated demand). An MMR rating for GR will come once we have at least 100 matches played to calibrate against.',
  tag: 'release',
  created_at: '2026-04-18 10:00:00',
}
