export default {
  slug: 'v600-victory-city-rebuilt',
  title_ru: 'Город побед перерождён',
  title_en: 'Victory City reborn',
  body_ru: 'Раньше была странность: 1 выигранная партия = целый небоскрёб. Сыграл 5 партий — у тебя район из пяти высоток, это было нелогично для игры про столбики из 11 блоков.\n\nТеперь 1 победа = от 1 до 5 кирпичей (за живого соперника +1, за Hard AI +1, Extreme +2, Impossible +3, за золотую победу +1). Кирпичи укладываются хронологически в стойки по 11 — ровно как в самой игре. 11-й кирпич закрывает высотку. Если этот последний кирпич был особый (золотая виктория или Impossible AI) — сверху висит золотая корона.\n\nНаведи на любой этаж — увидишь конкретную победу которая его положила. Кликни на высотку — весь список побед из которых она сложена.\n\nЧто ещё нового:\n\n— Кнопка «Поделиться городом» рядом с канвасом. Даёт ссылку вида highriseheist.com/embed/city/123 — при вставке в Telegram, Discord, Reddit, BGG или любой блог появляется красивая карточка-превью с именем и силуэтом высоток. Есть и iframe-снипет для встраивания в свои сайты.\n\n— Кнопка «Сравнить с…» — выбираешь друга, игрока из топа или вводишь ник, открывается страница со своими и его городами бок-о-бок, с очками и лидером. Ссылка тоже имеет красивую карточку-превью в мессенджерах.\n\n— Запись 8-секундного облёта города в видео (кнопка в меню Снимка). Сохраняется как .webm/.mp4. На телефоне сразу уходит в share sheet — можно в один клик отправить в TikTok или истории Instagram.\n\n— Холл оф фейм (кнопка «Топ» в панели) — топ-20 игроков по размеру города, кирпичам, высоткам и коронам. Твоя строка подсвечена.\n\n— Добавили индикатор «Следующая высотка: 7/11 кирпичей» — видно сколько осталось до закрытия.\n\nНикакой миграции базы не было — все старые победы пересчитались автоматически. Если раньше было 30 высоток на 30 побед, теперь будет 5-7 высоток + одна строящаяся.',
  body_en: 'It used to be weird: 1 win equals an entire skyscraper. Played 5 games — you have a five-tower district, which made no sense for a game about stacks of 11 blocks.\n\nNow 1 win = 1–5 bricks (vs human +1, vs Hard AI +1, Extreme +2, Impossible +3, golden victory +1). Bricks stack chronologically into towers of 11 — just like in the game itself. The 11th brick closes the highrise. If that final brick was special (golden victory or Impossible AI), a golden crown sits on top.\n\nHover any floor — you see the specific win that placed it. Click a tower — full list of wins it was built from.\n\nAlso new:\n\n— “Share city” button next to the canvas. Gives a link like highriseheist.com/embed/city/123 — when pasted into Telegram, Discord, Reddit, BGG or any blog it shows a beautiful preview card with the player name and tower silhouettes. There is also an iframe snippet to embed in your own site.\n\n— “Compare with…” button — pick a friend, top player or type a username, opens a side-by-side page with both cities, scores and the leader. The link also has a nice preview card in messengers.\n\n— 8-second flythrough video recording (button in Snapshot menu). Saves as .webm/.mp4. On phone it goes straight to the share sheet — one tap to send to TikTok or Instagram stories.\n\n— Hall of Fame (“Top” button in the panel) — top 20 by city size, bricks, towers and crowns. Your row is highlighted.\n\n— Added a “Next highrise: 7/11 bricks” indicator showing how close the next tower is to closing.\n\nNo database migration was needed — all old wins recompiled automatically. If you used to have 30 towers from 30 wins, now you will have 5–7 towers plus one under construction.',
  tag: 'release',
  created_at: '2026-04-15 14:00:00',
}
