export default {
  slug: 'v601-tests-coverage',
  title_ru: 'Под капотом: +290 тестов и 3 скрытых бага',
  title_en: 'Under the hood: +290 tests and 3 hidden bugs',
  body_ru: 'Внутренняя стабилизация — нет новых фичей для игроков, но игра стала серьёзно надёжнее.\n\nТЕСТАМИ\n\nНаписано около 290 новых unit- и компонентных тестов. Общее покрытие выросло до 574 зелёных тестов. Каждый деплой теперь прогоняет их все перед выкаткой на прод.\n\nПокрыто:\n— движок Golden Rush (сервер + клиент)\n— основной 2p-движок (раньше не было ни одного теста на него)\n— валидация входов, античит, WS-сообщения\n— админ-аудит, ачивки, чат-рейтлимит, XP-движок\n— компонент туториала Golden Rush\n— сбор тренировочных данных, share-логика, victory-city хелперы\n\n3 СКРЫТЫХ БАГА\n\nПока писал тесты, нашёл три реальных проблемы:\n\n1. Инициализация БД: индекс idx_season_rewards_user в базовой схеме ссылался на таблицу которая создавалась только миграцией №5. На проде это не стреляло потому что БД уже существует с прошлых запусков и таблица уже есть. Но при первом fresh-запуске или в тестовой in-memory базе инициализация падала с ошибкой no such table. Починили порядок: сначала все CREATE TABLE, потом CREATE INDEX.\n\n2. Метка сложности AI: для строки "вроде как числа но не число" (такая дыра в данных) функция возвращала "Лёгкая" (потому что parseInt давал 0, а 0 < 150 = easy). Теперь возвращает null — как и для null/undefined. Семантика выдержана.\n\n3. Счётчик наград Golden Rush: если какой-то бонус равен 0, UI показал бы "+0 бриксов" отдельной строчкой. В реальности сервер шлёт ненулевые значения, но на всякий случай добавил фильтр > 0.\n\nCI БОРЬБА\n\nПока прогонял тесты в CI, пришлось выловить ещё кучу мелких вещей: обновил GitHub Actions с v4 на v5 (старые были deprecated с Node.js 20), добавил happy-dom и @testing-library/react для компонентных тестов, починил permission-denied при уплоаде на сервер (при импорте БД в тестах создавался файлик с правами только для owner, scp-контейнер не мог его упаковать в tar).\n\nЗАЧЕМ ЭТО ВСЁ\n\nТесты не делают игру лучше сегодня. Они делают её лучше в день когда я напишу новую фичу и случайно сломаю старый edge case — CI покажет красное до выкатки на прод. Баги которые нашлись за эту сессию — меня бы не укусили, а вот первый установивший Highrise Heist с нуля — да.',
  body_en: 'Internal stabilization — no new features for players, but the game is meaningfully more reliable.\n\nTESTS\n\nWrote around 290 new unit and component tests. Total coverage is up to 574 green tests. Every deploy now runs them all before rolling out to prod.\n\nCovered:\n— Golden Rush engine (server + client)\n— the main 2p engine (previously had zero tests)\n— input validation, anti-cheat, WS message validation\n— admin audit, achievements, chat rate-limit, XP engine\n— Golden Rush tutorial component\n— training data collector, share logic, Victory City helpers\n\n3 HIDDEN BUGS\n\nWhile writing tests I found three real issues:\n\n1. DB initialization: the idx_season_rewards_user index was declared in the base schema but the table itself was created only by migration #5. On prod this never fired because the DB already exists from previous runs and the table is already there. But on a fresh install or in-memory test DB, initialization crashed with "no such table". Fixed the order: CREATE TABLE first, CREATE INDEX after.\n\n2. AI difficulty label: for a string that "looks like a number but isn\'t" (data hole), the function returned "Easy" (because parseInt gave 0, and 0 < 150 = easy). Now returns null — same as for null/undefined. Semantics preserved.\n\n3. Golden Rush reward counter: if some bonus was 0, the UI would show "+0 bricks" as a separate line. In practice the server sends non-zero values, but added a > 0 filter just in case.\n\nCI BATTLE\n\nWhile running tests in CI had to fix a bunch of small things: upgraded GitHub Actions from v4 to v5 (old ones were deprecated along with Node.js 20), added happy-dom and @testing-library/react for component tests, fixed permission-denied on server upload (importing DB in tests created a file with owner-only permissions, scp container couldn\'t pack it into tar).\n\nWHY BOTHER\n\nTests don\'t make the game better today. They make it better the day I write a new feature and accidentally break an old edge case — CI will flash red before it ships. The bugs that showed up this session wouldn\'t have bitten me, but the first person installing Highrise Heist from scratch — yes.',
  tag: 'update',
  created_at: '2026-04-19 18:30:00',
}
