/**
 * Changelog — история версий
 * Написано от руки, без AI-генерации
 */
import { useI18n } from '../engine/i18n'

const VERSIONS = [
  {
    version: '4.6.1',
    date: '2026-04-03',
    title_ru: 'Spectator chat, сезонные награды, сложные головоломки, SEO',
    title_en: 'Spectator chat, season rewards, hard puzzles, SEO',
    changes_ru: [
      { type: 'new', text: 'Spectator chat: зрители могут писать в чат во время наблюдения за партией' },
      { type: 'new', text: 'Сезонные награды: top-10 в сезоне получают эксклюзивные достижения (champion/silver/bronze)' },
      { type: 'new', text: 'Головоломки: +4 новых шаблона (сложность 4-5, до 5 ходов, «Мастер-план»)' },
      { type: 'fix', text: 'SEO: sitemap обновлён — 22 URL с hreflang и lastmod для всех страниц' },
      { type: 'fix', text: 'Миграция БД v5: таблица season_rewards для сезонных наград' },
    ],
    changes_en: [
      { type: 'new', text: 'Spectator chat: viewers can send messages while watching a game' },
      { type: 'new', text: 'Season rewards: top-10 in season get exclusive achievements (champion/silver/bronze)' },
      { type: 'new', text: 'Puzzles: +4 new templates (difficulty 4-5, up to 5 moves, "Master Plan")' },
      { type: 'fix', text: 'SEO: sitemap updated — 22 URLs with hreflang and lastmod for all pages' },
      { type: 'fix', text: 'DB migration v5: season_rewards table for seasonal rewards' },
    ],
  },
  {
    version: '4.6.0',
    date: '2026-04-03',
    title_ru: 'Friend Challenge, CSS –81%, рефералы, share-карточки',
    title_en: 'Friend Challenge, CSS –81%, referrals, share cards',
    changes_ru: [
      { type: 'new', text: 'Friend Challenge: кнопка «Вызвать» в друзьях, входящие вызовы с таймером, создание комнаты' },
      { type: 'new', text: 'Share-карточка: имя игрока, рейтинг, ELO дельта, сложность AI, шрифт Outfit (680×400 canvas)' },
      { type: 'new', text: 'Реферальная система: уникальный код, ссылка ?ref=, +100 XP, вкладка «Пригласить»' },
      { type: 'new', text: 'Поле «Код друга» при регистрации (ручной ввод + автозаполнение из URL)' },
      { type: 'fix', text: 'app.css: 3093 → 595 строк (–81%). Разделён на 8 модулей: game, landing, themes, native и др.' },
      { type: 'fix', text: 'Node.js 20→22, PM2 fork, HTTPS+HSTS, UFW firewall, sqlite3 бэкап каждые 6ч' },
      { type: 'fix', text: 'Vite chunks (engine/charts), удалён gpu_weights.json (–8.1MB), дубликаты handlers' },
      { type: 'fix', text: 'ELO-график с линиями тиров, исправлены англ. дубликаты в changelog' },
    ],
    changes_en: [
      { type: 'new', text: 'Friend Challenge: "Challenge" button in friends, incoming challenges with timer, room creation' },
      { type: 'new', text: 'Share card: player name, rating, ELO delta, AI difficulty, Outfit font (680×400 canvas)' },
      { type: 'new', text: 'Referral system: unique code, ?ref= link, +100 XP, "Invite" tab in profile' },
      { type: 'new', text: 'Referral code field in registration (manual input + auto-fill from URL)' },
      { type: 'fix', text: 'app.css: 3093 → 595 lines (–81%). Split into 8 modules: game, landing, themes, native etc.' },
      { type: 'fix', text: 'Node.js 20→22, PM2 fork, HTTPS+HSTS, UFW firewall, sqlite3 backup every 6h' },
      { type: 'fix', text: 'Vite chunks (engine/charts), removed gpu_weights.json (–8.1MB), duplicate handlers' },
      { type: 'fix', text: 'ELO chart with tier lines, fixed English duplicates in changelog' },
    ],
  },
  {
    version: '4.5.2',
    date: '2026-04-03',
    title_ru: 'CSS рефакторинг — app.css разделён на модули',
    title_en: 'CSS refactor — app.css split into modules',
    changes_ru: [
      { type: 'fix', text: 'app.css: 3093 → 595 строк (–81%). Выделены 8 файлов: game, landing, themes, native и др.' },
      { type: 'fix', text: 'Game CSS: 654 строки (board, stands, chips, scoreboard, controls, result)' },
      { type: 'fix', text: 'Landing: 261, Темы: 298, Native: 470, Confetti: 465, Skins: 106 строк' },
      { type: 'new', text: 'Поле «Код друга» при регистрации (ручной ввод + автозаполнение из ?ref=)' },
      { type: 'fix', text: 'Share-карточка: шрифт Outfit. Кнопка «Скопировано» в рефералах' },
    ],
    changes_en: [
      { type: 'fix', text: 'app.css: 3093 → 595 lines (–81%). Extracted 8 files: game, landing, themes, native etc.' },
      { type: 'fix', text: 'Game CSS: 654 lines (board, stands, chips, scoreboard, controls, result)' },
      { type: 'fix', text: 'Landing: 261, Themes: 298, Native: 470, Confetti: 465, Skins: 106 lines' },
      { type: 'new', text: 'Referral code field in registration (manual input + auto-fill from ?ref=)' },
      { type: 'fix', text: 'Share card: Outfit font. Copied button in referrals' },
    ],
  },
  {
    version: '4.5.1',
    date: '2026-04-03',
    title_ru: 'Виральность — share-карточки и реферальная система',
    title_en: 'Virality — share cards and referral system',
    changes_ru: [
      { type: 'new', text: 'Share-карточка: имя игрока, рейтинг, сложность AI, стойки, брендинг' },
      { type: 'new', text: 'Реферальная система: уникальный код, ссылка ?ref=, +100 XP за каждого приглашённого' },
      { type: 'new', text: 'Вкладка «Пригласить» в профиле: ссылка, код, кнопка «Поделиться», статистика' },
      { type: 'new', text: 'Автоматический захват ?ref= из URL при первом визите' },
      { type: 'new', text: 'Миграция БД v4: таблица referrals, referral_code для каждого юзера' },
    ],
    changes_en: [
      { type: 'new', text: 'Share card: player name, rating, AI difficulty, stands, branding' },
      { type: 'new', text: 'Referral system: unique code, ?ref= link, +100 XP per invited player' },
      { type: 'new', text: '"Invite" tab in profile: link, code, share button, stats' },
      { type: 'new', text: 'Auto-capture ?ref= from URL on first visit' },
      { type: 'new', text: 'DB migration v4: referrals table, referral_code for each user' },
    ],
  },
  {
    version: '4.5.0',
    date: '2026-04-03',
    title_ru: 'Аудит кода — очистка, оптимизация, Node 22',
    title_en: 'Code audit — cleanup, optimization, Node 22',
    changes_ru: [
      { type: 'fix', text: 'Node.js 20 → 22.22.2 на VPS (Capacitor CLI требует 22+)' },
      { type: 'fix', text: 'Удалён мёртвый gpu_weights.json (8.1MB) — используется только .bin' },
      { type: 'fix', text: 'Удалены дублированные 404 и error handlers в server.js' },
      { type: 'fix', text: 'Удалён дублирующий setInterval очистки в middleware.js' },
      { type: 'fix', text: 'PM2: exec_mode fork вместо cluster (SQLite = один писатель)' },
      { type: 'fix', text: 'Удалён фейковый aggregateRating из JSON-LD (Google manual action risk)' },
      { type: 'fix', text: 'Исправлен v3.7 → v4.5.0 в native More tab' },
      { type: 'fix', text: 'setup-vps.sh обновлён на Node.js 22' },
      { type: 'new', text: 'Vite: manual chunks — engine и charts выделены в отдельные чанки' },
      { type: 'new', text: 'ELO-график: линии рейтинг-тиров (1200/1500/1800), точка текущего рейтинга' },
      { type: 'new', text: 'Error handler: логирование серверных ошибок в БД (error_reports)' },
    ],
    changes_en: [
      { type: 'fix', text: 'Node.js 20 → 22.22.2 on VPS (Capacitor CLI requires 22+)' },
      { type: 'fix', text: 'Removed dead gpu_weights.json (8.1MB) — only .bin is used' },
      { type: 'fix', text: 'Removed duplicate 404 and error handlers in server.js' },
      { type: 'fix', text: 'Removed duplicate setInterval cleanup in middleware.js' },
      { type: 'fix', text: 'PM2: fork mode instead of cluster (SQLite = single writer)' },
      { type: 'fix', text: 'Removed fake aggregateRating from JSON-LD (Google manual action risk)' },
      { type: 'fix', text: 'Fixed v3.7 → v4.5.0 in native More tab' },
      { type: 'fix', text: 'setup-vps.sh updated to Node.js 22' },
      { type: 'new', text: 'Vite: manual chunks — engine and charts split into separate chunks' },
      { type: 'new', text: 'ELO chart: rating tier lines (1200/1500/1800), current rating dot' },
      { type: 'new', text: 'Error handler: server errors now logged to DB (error_reports)' },
    ],
  },
  {
    version: '4.4',
    date: '2026-04-03',
    title_ru: 'Архитектурный аудит — 57 коммитов, 157 тестов, dist –59%',
    title_en: 'Architecture audit — 57 commits, 157 tests, dist –59%',
    changes_ru: [
      // Тесты и сборка
      { type: 'new', text: 'Тесты: 41 → 164 (+123). Движок, валидация, стресс, swap, placement, transfer, edge cases' },
      { type: 'new', text: 'dist: 14MB → 5.8MB (–59%) — GPU weights только binary, убран JSON fallback 8.1MB' },
      { type: 'new', text: 'CI/CD: test → build → backup DB → deploy. npm cache, BUILD_HASH для SW' },
      // Архитектура
      { type: 'new', text: 'GameContext v2: EventEmitter — 25 CustomEvent → 0, 5 window globals → 0, 4 polling → 0' },
      { type: 'new', text: 'Schema migrations (3): schema_version, runMigration(), автоматическое обновление DB' },
      { type: 'new', text: 'Smart Service Worker: cache-first assets, stale-while-revalidate images, network-first navigation' },
      { type: 'new', text: 'Graceful shutdown: уведомление WS игроков, закрытие DB, PM2 log rotation' },
      { type: 'new', text: 'DB maintenance: ежедневная очистка error_reports, WAL checkpoint, sqlite pragmas' },
      // Рефактор компонентов
      { type: 'new', text: 'Emoji-реакции в онлайн-игре: 👍🔥😮😂💪🎉 с floating-анимацией' },
      { type: 'new', text: 'Счётчик зрителей в онлайн-партии: 👁 N при наличии спектаторов' },
      { type: 'new', text: '🔊 Быстрое вкл/выкл звука в game toolbar без захода в настройки' },
      { type: 'new', text: 'Горячие клавиши: ? — overlay с 7 shortcuts, стилизованные kbd badges' },
      { type: 'new', text: '«Что нового» — popup с Snappy при первом визите после обновления' },
      { type: 'new', text: '6 новых карточек Snappy: think, wave, celebrate, sad, point, shock — 3 размера (sm/lg/full)' },
      { type: 'fix', text: 'Game.jsx: 1723 → 1489 (–234). Выделены: GameResultPanel, useSessionStats, useGameTimer, useGameLog' },
      { type: 'fix', text: 'Profile.jsx: 1394 → 979 (–415). Выделены: ProfileAccount, ProfileFriends, ProfileAnalytics' },
      { type: 'fix', text: 'Online.jsx: 696 → 614 (–82). Выделён: DailyChallenge' },
      // Фичи
      { type: 'new', text: 'Таб «Аккаунт»: смена пароля, экспорт данных JSON (GDPR), удаление аккаунта' },
      { type: 'new', text: 'Друзья: decline + remove endpoints + UI кнопки принять/отклонить' },
      { type: 'new', text: 'WS Reconnect UI: прогресс-бар попытки/макс, визуальная задержка' },
      { type: 'new', text: 'Matchmaking: поиск по рейтингу ELO ±200, справедливые пары' },
      { type: 'new', text: 'Online timers: серверная синхронизация ходов + обработка timeUp' },
      { type: 'new', text: 'Error reporting: ErrorBoundary + global handlers → server DB + admin endpoint' },
      { type: 'new', text: 'Health endpoint: версия, память, rooms, matchQueue, API stats, rateLimits, uptime' },
      { type: 'new', text: 'PWA Install Prompt: кнопка «Установить» на landing page' },
      { type: 'new', text: 'Online lobby: live games indicator, авто-загрузка активных комнат' },
      { type: 'new', text: 'Games API: пагинация (offset+total), статистика по сложности AI' },
      { type: 'new', text: 'Загрузка: Snappy вместо текста «Загрузка...» — float-анимация маскота' },
      // SEO и документация
      { type: 'new', text: 'SEO: BreadcrumbList + FAQPage JSON-LD, preconnect, noscript, hreflang, Telegram meta' },
      { type: 'new', text: '.env.example + README.md полная документация проекта' },
      // Безопасность
      { type: 'fix', text: 'Безопасность: Admin ENV, trust proxy, JWT 7d+auto-refresh, Permissions-Policy' },
      { type: 'fix', text: 'Anti-cheat: минимум 8 ходов для победы, replay validation, training data limit 100KB' },
      { type: 'fix', text: 'CSP: api.qrserver.com, Permissions-Policy: camera/microphone/geolocation off' },
      // Производительность
      { type: 'fix', text: 'GPU weights: 8.1MB JSON → 3.2MB binary (–60%), lazy load только для Hard+' },
      { type: 'fix', text: '6 SQL индексов, N+1→RANK() OVER, analytics LIMIT 2000, last_seen throttle' },
      { type: 'fix', text: 'Auth: 2×setInterval polling → StorageEvent + visibilitychange' },
      { type: 'fix', text: 'applySettings: 25 classList.toggle → data-attributes. collector: in-memory кеш' },
      { type: 'fix', text: 'Cache-Control: 7 endpoints (blog, stats, leaderboard). ETag, X-Response-Time' },
      { type: 'fix', text: 'CORS preflight cache 1ч, rate limiter cleanup, Nginx gzip level 6' },
      { type: 'fix', text: 'Nginx: HTML no-cache+no-store, assets max-age=1y+immutable, WS timeout 3600s' },
      { type: 'fix', text: 'CSS cleanup: 49 dead rules удалены (–150 строк), 3246→3095' },
    ],
    changes_en: [
      { type: 'new', text: 'Tests: 41 → 164 (+123). Engine, validation, stress, swap, placement, transfer, edge cases' },
      { type: 'new', text: 'dist: 14MB → 5.8MB (–59%) — GPU weights binary only, removed 8.1MB JSON fallback' },
      { type: 'new', text: 'CI/CD: test → build → backup DB → deploy. npm cache, BUILD_HASH for SW' },
      { type: 'new', text: 'GameContext v2: EventEmitter — 25 CustomEvents → 0, 5 window globals → 0, 4 polling → 0' },
      { type: 'new', text: 'Schema migrations (3): schema_version, runMigration(), automatic DB upgrades' },
      { type: 'new', text: 'Smart Service Worker: cache-first assets, stale-while-revalidate images, network-first navigation' },
      { type: 'new', text: 'Graceful shutdown: notify WS players, close DB, PM2 log rotation' },
      { type: 'new', text: 'DB maintenance: daily error_reports cleanup, WAL checkpoint, sqlite pragmas' },
      { type: 'fix', text: 'Game.jsx: 1723 → 1489 (–234). Extracted: GameResultPanel, useSessionStats, useGameTimer, useGameLog' },
      { type: 'fix', text: 'Profile.jsx: 1394 → 979 (–415). Extracted: ProfileAccount, ProfileFriends, ProfileAnalytics' },
      { type: 'fix', text: 'Online.jsx: 696 → 614 (–82). Extracted: DailyChallenge' },
      { type: 'new', text: 'Account tab: change password, export data JSON (GDPR), delete account' },
      { type: 'new', text: 'Friends: decline + remove endpoints + accept/decline UI buttons' },
      { type: 'new', text: 'WS Reconnect UI: progress bar with attempt/max, visual delay' },
      { type: 'new', text: 'Matchmaking: search by ELO rating ±200, fair pairing' },
      { type: 'new', text: 'Online timers: server-synced moves + timeUp handler' },
      { type: 'new', text: 'Error reporting: ErrorBoundary + global handlers → server DB + admin endpoint' },
      { type: 'new', text: 'Health endpoint: version, memory, rooms, matchQueue, API stats, rateLimits, uptime' },
      { type: 'new', text: 'PWA Install Prompt: "Install" button on landing page' },
      { type: 'new', text: 'Online lobby: live games indicator, auto-load active rooms' },
      { type: 'new', text: 'Games API: pagination (offset+total), stats by AI difficulty' },
      { type: 'new', text: 'Loading: Snappy mascot instead of "Loading..." text — float animation' },
      { type: 'new', text: 'SEO: BreadcrumbList + FAQPage JSON-LD, preconnect, noscript, hreflang, Telegram meta' },
      { type: 'new', text: '.env.example + README.md full project documentation' },
      { type: 'fix', text: 'Security: Admin ENV, trust proxy, JWT 7d+auto-refresh, Permissions-Policy' },
      { type: 'fix', text: 'Anti-cheat: min 8 turns to win, replay validation, training data limit 100KB' },
      { type: 'fix', text: 'CSP: api.qrserver.com, Permissions-Policy: camera/microphone/geolocation off' },
      { type: 'fix', text: 'GPU weights: 8.1MB JSON → 3.2MB binary (–60%), lazy load for Hard+ only' },
      { type: 'fix', text: '6 SQL indexes, N+1→RANK() OVER, analytics LIMIT 2000, last_seen throttle' },
      { type: 'fix', text: 'Auth: 2×setInterval polling → StorageEvent + visibilitychange' },
      { type: 'fix', text: 'applySettings: 25 classList.toggle → data-attributes. collector: in-memory cache' },
      { type: 'fix', text: 'Cache-Control: 7 endpoints (blog, stats, leaderboard). ETag, X-Response-Time' },
      { type: 'fix', text: 'CORS preflight cache 1h, rate limiter cleanup, Nginx gzip level 6' },
      { type: 'fix', text: 'Nginx: HTML no-cache+no-store, assets max-age=1y+immutable, WS timeout 3600s' },
      { type: 'fix', text: 'CSS cleanup: 49 dead rules удалены (–150 строк), 3246→3095' },
    ],
  },
  {
    version: '4.3',
    date: '2026-04-02',
    title_ru: 'Ranked matchmaking, таймеры, аналитика, SEO, 24 настройки',
    title_en: 'Ranked matchmaking, timers, analytics, SEO, 24 settings',
    changes_ru: [
      { type: 'new', text: 'Ranked matchmaking — подбор по ELO (±200, расширяется со временем). Рейтинг оппонента виден до матча' },
      { type: 'new', text: 'Online таймеры — серверная синхронизация, время вычитается при каждом ходе' },
      { type: 'new', text: 'SEO: path routing — /game, /rules, /en/game. 16 индексируемых страниц вместо 2' },
      { type: 'new', text: '10 новых настроек: сложность AI, стартовый экран, авто-реванш, Zen mode, лог ходов, подписи стоек, приватность, экспорт данных' },
      { type: 'new', text: 'Вкладка «Аналитика» — 15 метрик: винрейт по сложности, тренд, активность по часам/дням, распределение счёта, comeback rate' },
      { type: 'new', text: 'Replay sharing — сохраняйте партии и делитесь ссылкой' },
      { type: 'new', text: 'Конфетти при победе + Error Boundary + анимация доски' },
      { type: 'new', text: 'Openings: 8 дебютов, Swap%, тепловая карта переносов, вкладка «Стратегия»' },
      { type: 'new', text: 'Лендинг: 6 тем с падающими блоками, 6 карточек фич с живыми анимациями' },
      { type: 'fix', text: 'Звуки подключены (7 эффектов: были написаны но не вызывались)' },
      { type: 'fix', text: 'WS reconnect: exponential backoff (1→30s), 15 попыток, session restore' },
      { type: 'fix', text: 'Input sanitization + автобэкап БД каждые 6 часов' },
    ],
    changes_en: [
      { type: 'new', text: 'Ranked matchmaking — ELO-based pairing (±200, expands over time). Opponent rating shown' },
      { type: 'new', text: 'Online timers — server-side sync, time deducted per move' },
      { type: 'new', text: 'SEO: path routing — /game, /rules, /en/game. 16 indexable pages' },
      { type: 'new', text: '10 new settings: AI difficulty, start screen, auto-rematch, Zen mode, move log, stand labels, privacy, data export' },
      { type: 'new', text: 'Analytics tab — 15 metrics: win rate by difficulty, trend, activity by hour/day, score distribution, comeback rate' },
      { type: 'new', text: 'Replay sharing — save games and share links' },
      { type: 'new', text: 'Confetti on victory + Error Boundary + board intro animation' },
      { type: 'new', text: 'Openings: 8 openings, Swap%, transfer heatmap, Strategy tab with 6 tactics' },
      { type: 'new', text: 'Landing: 6 themes with falling blocks, 6 feature cards with live animations' },
      { type: 'fix', text: 'Sound effects hooked up (7 effects: were written but never called)' },
      { type: 'fix', text: 'WS reconnect: exponential backoff (1→30s), 15 attempts, session restore' },
      { type: 'fix', text: 'Input sanitization + auto DB backup every 6 hours' },
    ],
  },
  {
    version: '4.2',
    date: '2026-04-02',
    title_ru: 'Маскот Снуппи, терминология, симулятор, онлайн-скины',
    title_en: 'Mascot Snoopy, terminology, simulator, online skins',
    changes_ru: [
      { type: 'new', text: 'Маскот Снуппи — енот-строитель на 10 страницах: лендинг, результат партии, головоломки, уроки, правила, профиль, onboarding. 6 поз, CSS-анимации' },
      { type: 'new', text: 'Терминология: фишка → блок, закрытие → достройка, стойка с 11 блоками = высотка. Обновлены все тексты: i18n, правила, уроки, лендинг, настройки, головоломки' },
      { type: 'new', text: 'Симулятор: 2 новых параметра — «блоков за ход» (1-6) и «стоек за ход» (1-5). Исследуйте альтернативные варианты правил' },
      { type: 'new', text: 'Онлайн: скины передаются оппоненту через WebSocket. Бейдж с выбранными скинами виден во время игры' },
      { type: 'fix', text: 'Кнопка «Отменить перенос» теперь видна после выбора переноса (когда расставляете блоки)' },
      { type: 'fix', text: 'Крупный шрифт включён по умолчанию' },
      { type: 'fix', text: 'Архитектура: server.js разбит на 9 route-модулей (1646 → 177 строк), CORS закрыт, global error handler, 41 тест на движок' },
    ],
    changes_en: [
      { type: 'new', text: 'Mascot Snoopy — raccoon builder on 10 pages: landing, game result, puzzles, lessons, rules, profile, onboarding. 6 poses, CSS animations' },
      { type: 'new', text: 'Terminology: chip → block, closing → completing, stand with 11 blocks = highrise. All texts updated: i18n, rules, lessons, landing, settings, puzzles' },
      { type: 'new', text: 'Simulator: 2 new parameters — "blocks per turn" (1-6) and "stands per turn" (1-5). Explore alternative rule variants' },
      { type: 'new', text: 'Online: skins transmitted to opponent via WebSocket. Skin badge visible during games' },
      { type: 'fix', text: 'Cancel transfer button now visible after selecting a transfer (during block placement phase)' },
      { type: 'fix', text: 'Large text enabled by default' },
      { type: 'fix', text: 'Architecture: server.js split into 9 route modules (1646 → 177 lines), CORS hardened, global error handler, 41 engine tests' },
    ],
  },
  {
    version: '4.1',
    date: '2026-04-01',
    title_ru: 'UI polish: темы, скины, профиль, формы',
    title_en: 'UI polish: themes, skins, profile, forms',
    changes_ru: [
      { type: 'new', text: 'Sakura (вишнёвая) и Retro (CRT терминал) — 2 новые темы, итого 11' },
      { type: 'new', text: 'Arctic переписана — тёмно-ледяная с голубым свечением (была светлой)' },
      { type: 'new', text: 'Визуальный SkinShop: мини-доска для каждой темы, стопки фишек и стойки с текстурой' },
      { type: 'fix', text: 'Каждая тема: 10–21 CSS правил (board glow, chip shadows, gradient стойки, neon text-shadow)' },
      { type: 'fix', text: 'Профиль: градиентный header, level badge, XP bar с glow, SVG checkmarks в ачивках' },
      { type: 'fix', text: 'Global: стилизованные input/select с focus-ring, кастомный scrollbar, ::selection' },
      { type: 'fix', text: 'Все hardcoded цвета → CSS vars. Все темы полностью theme-aware' },
      { type: 'fix', text: 'SVG иконки вместо emoji (puzzle sun, trophy, bolt, pin, checkmarks)' },
      { type: 'fix', text: 'Блог: исправлены числа в старых постах, удалены дубли, v4.0 закреплён' },
    ],
    changes_en: [
      { type: 'new', text: 'Sakura (cherry blossom) and Retro (CRT terminal) — 2 new themes, 11 total' },
      { type: 'new', text: 'Arctic rewritten — dark icy with blue glow (was light)' },
      { type: 'new', text: 'Visual SkinShop: mini-board per theme, chip stacks, textured stands' },
      { type: 'fix', text: 'Each theme: 10–21 CSS rules (board glow, chip shadows, gradient stands, neon text-shadow)' },
      { type: 'fix', text: 'Profile: gradient header, level badge, XP bar with glow, SVG checkmarks' },
      { type: 'fix', text: 'Global: styled input/select with focus-ring, custom scrollbar, ::selection' },
      { type: 'fix', text: 'All hardcoded colors → CSS vars. All themes fully theme-aware' },
      { type: 'fix', text: 'SVG icons instead of emoji (puzzle sun, trophy, bolt, pin, checkmarks)' },
      { type: 'fix', text: 'Blog: fixed numbers in old posts, removed duplicates, v4.0 pinned' },
    ],
  },
  {
    version: '4.0',
    date: '2026-04-01',
    title_ru: 'AI анализ, Puzzle Rush, Arena, уроки, 11 тем, 8 скинов фишек, 9 скинов стоек',
    title_en: 'AI review, Puzzle Rush, Arena, lessons, 11 themes, 8 chip skins, 9 stand skins',
    changes_ru: [
      { type: 'new', text: 'AI Game Review — анализ каждого хода: отличный/хороший/ошибка/грубая ошибка. Accuracy %, навигация по replay' },
      { type: 'new', text: 'Puzzle Rush — реши максимум головоломок за 3 минуты. +10 сек за правильную, -15 за ошибку. Leaderboard' },
      { type: 'new', text: 'Live Arena — турнирный режим Swiss system, 4 раунда, live таблица, XP для топ-3' },
      { type: 'new', text: '5 интерактивных уроков: основы → перенос → золотая → закрытие → стратегия. XP за каждый' },
      { type: 'new', text: '7 новых тем: Ocean, Sunset, Forest, Royal, Sakura, Arctic, Retro (всего 11)' },
      { type: 'new', text: '8 скинов фишек: Classic, Flat, Round, Glass, Metal, Candy, Pixel, Glow' },
      { type: 'new', text: '9 скинов стоек: Classic, Marble, Concrete, Bamboo, Obsidian, Crystal, Rust, Void, Ice' },
      { type: 'new', text: 'Магазин скинов (Skin Shop) — popup с live preview, level-locked скины' },
      { type: 'new', text: 'Animated board — screen shake при закрытии, 3D perspective, golden pulse' },
      { type: 'fix', text: 'Палитра под лого — accent coral→teal, 607 CSS var() в JSX' },
    ],
    changes_en: [
      { type: 'new', text: 'AI Game Review — analyze every move: excellent/good/inaccuracy/mistake/blunder. Accuracy %, replay navigation' },
      { type: 'new', text: 'Puzzle Rush — solve max puzzles in 3 minutes. +10 sec correct, -15 wrong. Leaderboard' },
      { type: 'new', text: 'Live Arena — Swiss tournament system, 4 rounds, live standings, XP for top 3' },
      { type: 'new', text: '5 interactive lessons: basics → transfer → golden → closing → strategy. XP for each' },
      { type: 'new', text: '7 new themes: Ocean, Sunset, Forest, Royal, Sakura, Arctic, Retro (11 total)' },
      { type: 'new', text: '8 chip skins: Classic, Flat, Round, Glass, Metal, Candy, Pixel, Glow' },
      { type: 'new', text: '9 stand skins: Classic, Marble, Concrete, Bamboo, Obsidian, Crystal, Rust, Void, Ice' },
      { type: 'new', text: 'Skin Shop — popup with live preview, level-locked skins' },
      { type: 'new', text: 'Animated board — screen shake on close, 3D perspective, golden pulse' },
      { type: 'fix', text: 'Color palette aligned with logo — accent coral→teal, 607 CSS var() in JSX' },
      { type: 'fix', text: 'All 26 components fully theme-aware (607 CSS var() in JSX)' },
    ],
  },
  {
    version: '3.9',
    date: '2026-03-31',
    title_ru: 'Retention: стрики, миссии, XP, auto-difficulty',
    title_en: 'Retention: streaks, missions, XP, auto-difficulty',
    changes_ru: [
      { type: 'new', text: 'Login streak — серия входов с календарём (30 дней), streak freeze 1/мес' },
      { type: 'new', text: 'Daily missions — 3 задания в день из пула 8, XP за выполнение + бонус 100 XP за все 3' },
      { type: 'new', text: 'XP / Level system — 20 XP за победу, 5 за поражение, level * 100 XP до следующего' },
      { type: 'new', text: 'AI auto-difficulty — после 3 поражений подряд кнопка «Попробовать полегче?»' },
      { type: 'new', text: 'First Win celebration — fullscreen popup со звездой при первой победе в жизни' },
      { type: 'new', text: 'Missions auto-tracking — прогресс миссий обновляется автоматически (Game + Puzzles)' },
      { type: 'new', text: 'Streak popup — toast при входе с текущей серией и рекордом' },
      { type: 'fix', text: 'Блог — принудительное обновление дат, хронологический порядок (12 постов)' },
    ],
    changes_en: [
      { type: 'new', text: 'Login streak — daily streak with calendar (30 days), streak freeze 1/month' },
      { type: 'new', text: 'Daily missions — 3 per day from pool of 8, XP rewards + 100 XP bonus for all 3' },
      { type: 'new', text: 'XP / Level system — 20 XP per win, 5 per loss, level * 100 XP to next' },
      { type: 'new', text: 'AI auto-difficulty — after 3 losses suggests easier level' },
      { type: 'new', text: 'First Win celebration — fullscreen star popup on first ever victory' },
      { type: 'new', text: 'Missions auto-tracking — progress updates automatically (Game + Puzzles)' },
      { type: 'new', text: 'Streak popup — toast on login showing current streak and best' },
      { type: 'fix', text: 'Blog — forced date update, chronological order (12 posts)' },
    ],
  },
  {
    version: '3.8',
    date: '2026-03-31',
    title_ru: 'Аудит, безопасность, полный i18n',
    title_en: 'Audit, security, full i18n',
    changes_ru: [
      { type: 'new', text: 'Game result — fullscreen overlay на мобильных с анимацией' },
      { type: 'new', text: 'ELO дельта (+12 / -8) отображается после каждой партии' },
      { type: 'new', text: 'PvP Undo — кнопка отмены последнего хода' },
      { type: 'new', text: 'Яндекс.Метрика (вебвизор, карта кликов)' },
      { type: 'new', text: 'Firebase Push — код готов (регистрация токенов)' },
      { type: 'new', text: 'Google Play signing config (keystore.properties)' },
      { type: 'fix', text: 'XSS в чате — HTML tags stripped на сервере' },
      { type: 'fix', text: 'WS rate limiting — 15 msg/sec max' },
      { type: 'fix', text: '401 auto-logout — протухший JWT очищается автоматически' },
      { type: 'fix', text: 'SW hotfix — авто-очистка сломанного кеша для всех пользователей' },
      { type: 'fix', text: 'WebP изображения — logo, OG, icons (-80% трафика)' },
      { type: 'fix', text: 'CSS дубли убраны (site-content 3→1, stand 2→1, chip 2→1)' },
      { type: 'fix', text: 'i18n полный — Game, Online, Profile, 26 ачивок с descEn' },
      { type: 'fix', text: 'aria-labels на все icon-only кнопки' },
      { type: 'fix', text: 'Username XSS sanitization при регистрации' },
      { type: 'fix', text: 'Sitemap обновлён — удалены мёртвые ссылки' },
    ],
    changes_en: [
      { type: 'new', text: 'Game result — fullscreen overlay on mobile with animation' },
      { type: 'new', text: 'ELO delta (+12 / -8) displayed after each game' },
      { type: 'new', text: 'PvP Undo — undo last move button' },
      { type: 'new', text: 'Yandex Metrika (webvisor, click map)' },
      { type: 'new', text: 'Firebase Push — code ready (token registration)' },
      { type: 'new', text: 'Google Play signing config (keystore.properties)' },
      { type: 'fix', text: 'XSS in chat — HTML tags stripped on server' },
      { type: 'fix', text: 'WS rate limiting — 15 msg/sec max' },
      { type: 'fix', text: '401 auto-logout — expired JWT auto-cleared' },
      { type: 'fix', text: 'SW hotfix — auto-clear broken cache for all users' },
      { type: 'fix', text: 'WebP images — logo, OG, icons (-80% traffic)' },
      { type: 'fix', text: 'CSS duplicates removed (site-content 3→1, stand 2→1, chip 2→1)' },
      { type: 'fix', text: 'Full i18n — Game, Online, Profile, 26 achievements with descEn' },
      { type: 'fix', text: 'aria-labels on all icon-only buttons' },
      { type: 'fix', text: 'Username XSS sanitization on registration' },
      { type: 'fix', text: 'Sitemap updated — removed dead links' },
    ],
  },
  {
    version: '3.7',
    date: '2026-03-31',
    title_ru: 'Мобильное приложение, haptic, onboarding, новые логотипы',
    title_en: 'Mobile app, haptic feedback, onboarding, new logos',
    changes_ru: [
      { type: 'new', text: 'Мобильное приложение — полная адаптация UI для Android (Capacitor)' },
      { type: 'new', text: 'Haptic feedback — вибрация при каждом действии (размещение, перенос, закрытие, победа)' },
      { type: 'new', text: 'Onboarding — 4 экрана обучения при первом запуске (свайп, skip)' },
      { type: 'new', text: 'Новые логотипы — иконка, splash screen, header, OG-image' },
      { type: 'new', text: 'Privacy Policy — политика конфиденциальности RU/EN' },
      { type: 'new', text: 'Share app — поделиться приложением через нативный dialog' },
      { type: 'new', text: 'Rate app popup — предложение оценить после 5 побед' },
      { type: 'new', text: 'Offline detection — баннер "Нет сети" + AI работает без интернета' },
      { type: 'new', text: 'Доска растягивается на весь экран (flex layout), кнопки в зоне пальцев' },
      { type: 'new', text: 'Game result — fullscreen overlay на мобильных' },
      { type: 'new', text: 'Планшет — ограниченная ширина доски и tab bar' },
      { type: 'fix', text: 'Убрана пустота внизу экрана (.app padding 80px в native)' },
      { type: 'fix', text: 'Профиль: stats 2×2 на телефонах, табы горизонтальный скролл' },
      { type: 'fix', text: 'Puzzles grid не выходит за экран на 320px (min() fix)' },
      { type: 'fix', text: 'Фишки с border вместо тяжёлого box-shadow в native' },
      { type: 'fix', text: 'Landscape mode — компактные стойки, скрытые лейблы tab bar' },
    ],
    changes_en: [
      { type: 'new', text: 'Mobile app — full UI adaptation for Android (Capacitor)' },
      { type: 'new', text: 'Haptic feedback — vibration on every action (place, transfer, close, win)' },
      { type: 'new', text: 'Onboarding — 4 swipeable intro screens on first launch' },
      { type: 'new', text: 'New logos — app icon, splash screen, header, OG-image' },
      { type: 'new', text: 'Privacy Policy page (RU/EN)' },
      { type: 'new', text: 'Share app via native share dialog' },
      { type: 'new', text: 'Rate app popup after 5 wins' },
      { type: 'new', text: 'Offline detection — banner + AI works without internet' },
      { type: 'new', text: 'Board stretches to fill screen (flex layout), buttons in thumb zone' },
      { type: 'new', text: 'Game result — fullscreen overlay on mobile' },
      { type: 'new', text: 'Tablet — constrained board and tab bar width' },
      { type: 'fix', text: 'Removed empty space at bottom (.app padding 80px in native)' },
      { type: 'fix', text: 'Profile: 2×2 stats grid on phones, horizontal scroll tabs' },
      { type: 'fix', text: 'Puzzles grid overflow fix on 320px screens' },
      { type: 'fix', text: 'Chips with border instead of heavy box-shadow in native' },
      { type: 'fix', text: 'Landscape mode — compact stands, hidden tab labels' },
    ],
  },
  {
    version: '3.6',
    date: '2026-03-31',
    title_ru: 'Capacitor мобильное приложение',
    title_en: 'Capacitor mobile app',
    changes_ru: [
      { type: 'new', text: 'Android-приложение через Capacitor — bottom tab bar, нативный UI' },
      { type: 'new', text: 'Мобильный game bar с шестерёнкой настроек (bottom sheet)' },
      { type: 'new', text: 'More page — настройки, правила, блог, changelog, язык, аватар' },
      { type: 'new', text: 'Performance: убраны backdrop-filter, box-shadow, бесконечные анимации в native' },
      { type: 'new', text: 'Fetch interceptor: /api/ → snatch-highrise.com/api/ в native' },
      { type: 'new', text: 'Deep links: Android intent-filter для snatch-highrise.com' },
      { type: 'new', text: 'Safe area insets для notch и системной навигации' },
    ],
    changes_en: [
      { type: 'new', text: 'Android app via Capacitor — bottom tab bar, native UI' },
      { type: 'new', text: 'Mobile game bar with settings gear (bottom sheet)' },
      { type: 'new', text: 'More page — settings, rules, blog, changelog, language, avatar' },
      { type: 'new', text: 'Performance: removed backdrop-filter, box-shadow, infinite animations in native' },
      { type: 'new', text: 'Fetch interceptor: /api/ → snatch-highrise.com/api/ in native' },
      { type: 'new', text: 'Deep links: Android intent-filter for snatch-highrise.com' },
      { type: 'new', text: 'Safe area insets for notch and system navigation' },
    ],
  },
  {
    version: '3.5',
    date: '2026-03-30',
    title_ru: 'GPU-нейросеть, экстрим, рематч, спектатор, профили',
    title_en: 'GPU neural network, extreme, rematch, spectator, profiles',
    changes_ru: [
      { type: 'new', text: 'GPU-нейросеть в браузере — ResNet 840K параметров (v500, NVIDIA), значительно сильнее AI' },
      { type: 'new', text: 'Сложность «Экстрим» — 600 GPU-симуляций, самый сильный AI' },
      { type: 'new', text: 'Доучивание AI на партиях реальных игроков (retrain.py pipeline)' },
      { type: 'new', text: 'Серверная валидация ходов — движок на сервере, защита от gameOver эксплойта' },
      { type: 'new', text: 'Рематч в онлайн-режиме — кнопка после партии, сервер меняет стороны' },
      { type: 'new', text: 'Спектатор-режим — наблюдение за чужими партиями в реальном времени' },
      { type: 'new', text: 'Публичные профили — клик по нику в лидерборде открывает карточку игрока' },
      { type: 'new', text: 'Push-уведомления (Browser Notification API) — ваш ход, ничья, рематч' },
      { type: 'new', text: 'CMS: 84 хардкодных текста заменены на i18n, 65 новых ключей в админке' },
      { type: 'new', text: 'server.js разбит на модули: db.js, ws.js, server.js' },
      { type: 'new', text: 'Game.jsx декомпозиция: ReplayViewer.jsx, gameUtils.js (1424→1267 строк)' },
      { type: 'fix', text: 'Переименование лога «Стойки API» → «Snatch Highrise API»' },
      { type: 'fix', text: 'useI18n() добавлен в sub-компоненты Blog, Tutorial, Openings, Puzzles' },
      { type: 'fix', text: 'spectate-online: newGame reset, resign скрыт, back-to-lobby' },
    ],
    changes_en: [
      { type: 'new', text: 'GPU neural network in browser — ResNet 840K params (v500, NVIDIA), much stronger AI' },
      { type: 'new', text: 'Extreme difficulty — 600 GPU simulations, strongest AI level' },
      { type: 'new', text: 'AI retraining on real player games (retrain.py pipeline)' },
      { type: 'new', text: 'Server-side move validation — game engine on server, gameOver exploit fixed' },
      { type: 'new', text: 'Online rematch — button after game, server swaps sides automatically' },
      { type: 'new', text: 'Spectator mode — watch live games in real-time' },
      { type: 'new', text: 'Public profiles — click username in leaderboard to view player card' },
      { type: 'new', text: 'Push notifications (Browser Notification API) — your turn, draw, rematch' },
      { type: 'new', text: 'CMS: 84 hardcoded texts replaced with i18n, 65 new keys in admin' },
      { type: 'new', text: 'server.js split into modules: db.js, ws.js, server.js' },
      { type: 'new', text: 'Game.jsx decomposition: ReplayViewer.jsx, gameUtils.js (1424→1267 lines)' },
      { type: 'fix', text: 'Console log renamed "Стойки API" → "Snatch Highrise API"' },
      { type: 'fix', text: 'useI18n() added to Blog, Tutorial, Openings, Puzzles sub-components' },
      { type: 'fix', text: 'spectate-online: newGame reset, resign hidden, back-to-lobby' },
    ],
  },
  {
    version: '3.4',
    date: '2026-03-27',
    title_ru: 'UX по результатам тестирования',
    title_en: 'UX from playtesting',
    changes_ru: [
      { type: 'new', text: 'Правила переписаны с нуля — SVG-схемы вместо интерактивных демо' },
      { type: 'new', text: 'Стойки перевёрнуты — фишки растут снизу вверх' },
      { type: 'new', text: 'Счётчик фишек — всегда виден, красный при 9+, жёлтый при 7+' },
      { type: 'new', text: 'Призрачный перенос — видно откуда ушли и куда пришли фишки' },
      { type: 'new', text: 'Print & Play — белый фон, 70 фишек (было 55)' },
      { type: 'fix', text: 'Критический баг: Online стартовал AI вместо мультиплеера' },
      { type: 'fix', text: 'Пустые кнопки Share/Replay после resign' },
      { type: 'fix', text: 'Light тема — полная переработка (Apple-style)' },
    ],
    changes_en: [
      { type: 'new', text: 'Rules rewritten — SVG diagrams instead of interactive demos' },
      { type: 'new', text: 'Stands flipped — chips grow bottom-up' },
      { type: 'new', text: 'Chip counter — always visible, red at 9+, yellow at 7+' },
      { type: 'new', text: 'Ghost transfer — visual source/destination indicators' },
      { type: 'new', text: 'Print & Play — white bg, 70 chips (was 55)' },
      { type: 'fix', text: 'Critical bug: Online started AI instead of multiplayer' },
      { type: 'fix', text: 'Empty Share/Replay buttons after resign' },
      { type: 'fix', text: 'Light theme — full rework (Apple-style)' },
    ],
  },
  {
    version: '3.3',
    date: '2026-03-24',
    title_ru: 'Адаптивка, тема Wood, правила',
    title_en: 'Responsive, Wood theme, rules',
    changes_ru: [
      { type: 'new', text: '8 брейкпоинтов адаптивки (было 4) — от 1024px до 340px' },
      { type: 'new', text: 'Тема Wood полностью переработана: CSS текстуры дерева, inner shadow, стилизация фишек' },
      { type: 'new', text: 'Интерактивные схемы в правилах: перенос (4 шага), закрытие (3 шага), swap' },
      { type: 'new', text: 'Отдельная страница Changelog с историей всех версий' },
      { type: 'new', text: 'Обновлённый Print & Play PDF v3.2 с полными правилами' },
      { type: 'fix', text: 'Туториал центрирован по вертикали, текст переноса исправлен' },
      { type: 'fix', text: 'Футер: стили разделителей, ссылки Changelog/Правила/Print & Play' },
      { type: 'fix', text: 'Dropdown «Ещё» не пропадает при наведении' },
      { type: 'fix', text: 'Админка адаптивна: горизонтальные табы на мобилке' },
      { type: 'fix', text: 'Убран автор из лендинга' },
    ],
    changes_en: [
      { type: 'new', text: '8 responsive breakpoints (was 4) — from 1024px to 340px' },
      { type: 'new', text: 'Wood theme fully reworked: CSS wood grain textures, inner shadows, styled chips' },
      { type: 'new', text: 'Interactive rule diagrams: transfer (4 steps), closing (3 steps), swap' },
      { type: 'new', text: 'Dedicated Changelog page with full version history' },
      { type: 'new', text: 'Updated Print & Play PDF v3.2 with complete rules' },
      { type: 'fix', text: 'Tutorial vertically centered, transfer text corrected' },
      { type: 'fix', text: 'Footer: divider styles, Changelog/Rules/Print & Play links' },
      { type: 'fix', text: '"More" dropdown no longer disappears on hover' },
      { type: 'fix', text: 'Admin panel responsive: horizontal tabs on mobile' },
      { type: 'fix', text: 'Removed author from landing page' },
    ],
  },
  {
    version: '3.2',
    date: '2026-03-24',
    title_ru: 'Админ-панель и безопасность',
    title_en: 'Admin panel & security',
    changes_ru: [
      { type: 'new', text: 'Полноценная админ-панель: пользователи, партии, блог, сезоны, сервер' },
      { type: 'new', text: 'Управление блогом через админку (создание, редактирование, удаление)' },
      { type: 'new', text: 'Мониторинг комнат и очереди в реальном времени' },
      { type: 'new', text: 'Статистика ачивок и обучающих данных' },
      { type: 'fix', text: 'WebSocket аутентификация — токен передаётся при подключении' },
      { type: 'fix', text: 'Валидация результатов партий на сервере (защита от накрутки)' },
      { type: 'fix', text: 'Исправлена проверка прав администратора в блоге' },
      { type: 'fix', text: 'Helmet CSP включён, CORS ограничен' },
      { type: 'fix', text: 'Исправлен баг с двойной отправкой чат-сообщений в онлайне' },
      { type: 'perf', text: 'Game и Online загружаются только при первом посещении' },
      { type: 'perf', text: 'Service Worker обновляется автоматически при каждом деплое' },
    ],
    changes_en: [
      { type: 'new', text: 'Full admin panel: users, games, blog, seasons, server monitoring' },
      { type: 'new', text: 'Blog management through admin (create, edit, delete)' },
      { type: 'new', text: 'Live room & matchmaking queue monitoring' },
      { type: 'new', text: 'Achievement and training data stats' },
      { type: 'fix', text: 'WebSocket authentication — token sent on connection' },
      { type: 'fix', text: 'Server-side game result validation (anti-cheat)' },
      { type: 'fix', text: 'Fixed admin permission check in blog endpoints' },
      { type: 'fix', text: 'Helmet CSP enabled, CORS restricted' },
      { type: 'fix', text: 'Fixed duplicate chat messages in online mode' },
      { type: 'perf', text: 'Game and Online lazy-loaded on first visit only' },
      { type: 'perf', text: 'Service Worker auto-updates on each deploy' },
    ],
  },
  {
    version: '3.1',
    date: '2026-03-20',
    title_ru: 'Интерактивные правила и схемы',
    title_en: 'Interactive rules & diagrams',
    changes_ru: [
      { type: 'new', text: 'Интерактивная схема переноса — 4 шага с анимацией' },
      { type: 'new', text: 'Интерактивная схема закрытия стойки — 3 шага' },
      { type: 'new', text: 'Демо Swap Rule с кнопкой смены цветов' },
      { type: 'new', text: 'Расширенные правила: все нюансы из оригинального ТЗ' },
      { type: 'fix', text: 'Стили футера (разделители и расположение)' },
      { type: 'new', text: 'Ссылки в подвале: Changelog, Правила, Print & Play' },
    ],
    changes_en: [
      { type: 'new', text: 'Interactive transfer diagram — 4 animated steps' },
      { type: 'new', text: 'Interactive stand closing diagram — 3 steps' },
      { type: 'new', text: 'Swap Rule demo with color swap button' },
      { type: 'new', text: 'Expanded rules: all nuances from original spec' },
      { type: 'fix', text: 'Footer styles (dividers and layout)' },
      { type: 'new', text: 'Footer links: Changelog, Rules, Print & Play' },
    ],
  },
  {
    version: '3.0',
    date: '2026-03-15',
    title_ru: 'Масштабное обновление',
    title_en: 'Major update',
    changes_ru: [
      { type: 'new', text: '26 ачивок (было 14) с цветовыми категориями: бронза, серебро, золото, алмаз' },
      { type: 'new', text: 'Рейтинговые сезоны — каждый месяц новый, свой лидерборд' },
      { type: 'new', text: '14 настроек: таймер, стиль фишек, плотность доски, дальтоники, крупный текст' },
      { type: 'new', text: 'Полная мультиязычность RU/EN — весь интерфейс переведён' },
      { type: 'new', text: 'Resign и предложение ничьей в онлайне' },
      { type: 'new', text: 'Quick-chat: gg, gl, nice, wp, !' },
      { type: 'new', text: 'Случайный матчмейкинг — кнопка «Найти соперника»' },
      { type: 'new', text: 'Авторизация в шапке — аватар с рейтингом' },
      { type: 'new', text: 'Лендинг с scroll-анимациями (4 итерации дизайна)' },
      { type: 'perf', text: 'Error Boundary + lazy loading (11 компонентов)' },
      { type: 'perf', text: 'Hash routing: #game, #blog, #puzzles — back/forward работает' },
      { type: 'new', text: 'OG-теги, JSON-LD, robots.txt, sitemap' },
      { type: 'new', text: 'Accessibility: aria-labels, focus-visible, skip-link, keyboard nav' },
      { type: 'new', text: 'Service Worker: network-first, не кеширует API' },
    ],
    changes_en: [
      { type: 'new', text: '26 achievements (was 14) with color tiers: bronze, silver, gold, diamond' },
      { type: 'new', text: 'Ranked seasons — monthly, each with its own leaderboard' },
      { type: 'new', text: '14 settings: timer, chip style, board density, colorblind, large text' },
      { type: 'new', text: 'Full RU/EN internationalization' },
      { type: 'new', text: 'Resign and draw offer in online mode' },
      { type: 'new', text: 'Quick chat: gg, gl, nice, wp, !' },
      { type: 'new', text: 'Random matchmaking — "Find opponent" button' },
      { type: 'new', text: 'Auth in header — avatar with rating' },
      { type: 'new', text: 'Landing page with scroll animations' },
      { type: 'perf', text: 'Error Boundary + lazy loading (11 components)' },
      { type: 'perf', text: 'Hash routing with browser back/forward support' },
      { type: 'new', text: 'OG tags, JSON-LD, robots.txt, sitemap' },
      { type: 'new', text: 'Accessibility: aria-labels, focus-visible, skip-link' },
      { type: 'new', text: 'Service Worker: network-first, skips API caching' },
    ],
  },
  {
    version: '2.0',
    date: '2026-02-20',
    title_ru: 'Онлайн мультиплеер и головоломки',
    title_en: 'Online multiplayer & puzzles',
    changes_ru: [
      { type: 'new', text: 'Онлайн мультиплеер по ссылке — WebSocket, QR-код, серии 3/5' },
      { type: 'new', text: 'Ежедневные и еженедельные головоломки с лидербордами' },
      { type: 'new', text: 'Банк из 50 головоломок (3 уровня сложности)' },
      { type: 'new', text: 'Ежедневный челлендж со стартовой позицией' },
      { type: 'new', text: 'Система друзей — запросы, принятие' },
      { type: 'new', text: 'История партий (50 последних)' },
      { type: 'new', text: '4 темы: Dark, Neon, Wood, Light' },
      { type: 'new', text: '4 звуковых пака: classic, minimal, retro, off' },
      { type: 'new', text: 'Print & Play PDF: 3 страницы A4' },
    ],
    changes_en: [
      { type: 'new', text: 'Online multiplayer via link — WebSocket, QR code, best-of-3/5' },
      { type: 'new', text: 'Daily and weekly puzzles with leaderboards' },
      { type: 'new', text: '50 puzzle bank (3 difficulty levels)' },
      { type: 'new', text: 'Daily challenge with starting position' },
      { type: 'new', text: 'Friends system — requests, acceptance' },
      { type: 'new', text: 'Game history (last 50)' },
      { type: 'new', text: '4 themes: Dark, Neon, Wood, Light' },
      { type: 'new', text: '4 sound packs: classic, minimal, retro, off' },
      { type: 'new', text: 'Print & Play PDF: 3 A4 pages' },
    ],
  },
  {
    version: '1.0',
    date: '2026-01-15',
    title_ru: 'Первый релиз',
    title_en: 'First release',
    changes_ru: [
      { type: 'new', text: 'Полная реализация правил: 10 стоек, 11 фишек, золотая стойка' },
      { type: 'new', text: 'AI на AlphaZero: MCTS + нейросеть, 3 уровня сложности' },
      { type: 'new', text: 'GPU-обучение: 1146 итераций, loss 0.098, win rate 97%' },
      { type: 'new', text: 'Баланс P1/P2: 50:50 на 239K партий' },
      { type: 'new', text: 'Swap rule для компенсации преимущества первого хода' },
      { type: 'new', text: 'Режимы: vs AI, PvP локально, AI vs AI (наблюдение)' },
      { type: 'new', text: 'ELO рейтинг и профиль игрока' },
      { type: 'new', text: '12 аватаров на выбор' },
      { type: 'new', text: 'Блог с новостями разработки' },
    ],
    changes_en: [
      { type: 'new', text: 'Full game rules: 10 stands, 11 chips, golden stand' },
      { type: 'new', text: 'AlphaZero AI: MCTS + neural network, 3 difficulty levels' },
      { type: 'new', text: 'GPU training: 1146 iterations, loss 0.098, win rate 97%' },
      { type: 'new', text: 'P1/P2 balance: 50:50 across 239K games' },
      { type: 'new', text: 'Swap rule to compensate first-move advantage' },
      { type: 'new', text: 'Modes: vs AI, local PvP, AI vs AI (spectate)' },
      { type: 'new', text: 'ELO rating and player profile' },
      { type: 'new', text: '12 avatars to choose from' },
      { type: 'new', text: 'Dev blog' },
    ],
  },
]

const TYPE_STYLE = {
  new: { label: 'NEW', color: 'var(--green)', bg: 'rgba(61,214,140,0.1)' },
  fix: { label: 'FIX', color: 'var(--coral)', bg: 'rgba(240,101,74,0.1)' },
  perf: { label: 'PERF', color: 'var(--p1)', bg: 'rgba(74,158,255,0.1)' },
}

function formatDate(dateStr, lang) {
  const d = new Date(dateStr)
  if (lang === 'en') return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  return d.toLocaleDateString('ru-RU', { year: 'numeric', month: 'long', day: 'numeric' })
}

export default function Changelog() {
  const { lang } = useI18n()
  const en = lang === 'en'

  return (
    <div style={{ maxWidth: 700, margin: '0 auto' }}>
      <div style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: 'var(--ink)', margin: 0 }}>Changelog</h2>
        <p style={{ fontSize: 13, color: 'var(--ink3)', marginTop: 6 }}>
          {en ? 'What changed and when. Every update in one place.' : 'Что менялось и когда. Все обновления в одном месте.'}
        </p>
      </div>

      <div style={{ position: 'relative', paddingLeft: 28 }}>
        {/* Вертикальная линия */}
        <div style={{
          position: 'absolute', left: 8, top: 8, bottom: 0, width: 2,
          background: 'linear-gradient(to bottom, var(--accent), var(--surface3))',
          borderRadius: 1,
        }} />

        {VERSIONS.map((v, vi) => {
          const changes = en ? v.changes_en : v.changes_ru
          const title = en ? v.title_en : v.title_ru

          return (
            <div key={v.version} style={{ marginBottom: vi < VERSIONS.length - 1 ? 36 : 0, position: 'relative' }}>
              {/* Точка на линии */}
              <div style={{
                position: 'absolute', left: -24, top: 6, width: 14, height: 14,
                borderRadius: '50%', background: vi === 0 ? 'var(--accent)' : 'var(--surface3)',
                border: `2px solid ${vi === 0 ? 'var(--accent)' : 'var(--surface3)'}`,
              }} />

              {/* Заголовок версии */}
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 10, flexWrap: 'wrap' }}>
                <span style={{
                  fontSize: 18, fontWeight: 700, color: 'var(--ink)',
                  fontFamily: "'DM Serif Display', serif",
                }}>v{v.version}</span>
                <span style={{ fontSize: 14, color: 'var(--ink2)', fontWeight: 500 }}>{title}</span>
                <span style={{ fontSize: 11, color: 'var(--ink3)', marginLeft: 'auto' }}>{formatDate(v.date, lang)}</span>
              </div>

              {/* Список изменений */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {changes.map((c, ci) => {
                  const t = TYPE_STYLE[c.type] || TYPE_STYLE.new
                  return (
                    <div key={ci} style={{ display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                      <span style={{
                        fontSize: 9, fontWeight: 700, padding: '2px 6px', borderRadius: 3,
                        background: t.bg, color: t.color, flexShrink: 0, marginTop: 2,
                        letterSpacing: 0.5, lineHeight: '14px',
                      }}>{t.label}</span>
                      <span style={{ fontSize: 13, color: 'var(--ink2)', lineHeight: 1.5 }}>{c.text}</span>
                    </div>
                  )
                })}
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
